#ifndef VMCALL_CODES_H
#define VMCALL_CODES_H

// Defines the API for commands sent to the hypervisor via VMCALL.
typedef enum _VMCALL_CODE
{
    VMCALL_GET_STATUS,
    VMCALL_CLOAK_INT3_PAGE,
    VMCALL_UNCLOAK_INT3_PAGE,
    VMCALL_SET_MSR_SPOOF,
    VMCALL_SET_CPUID_SPOOF,
    VMCALL_SET_RDTSC_SPOOF,
    VMCALL_RUN_NTOSKRNL_PATCH_SCAN,
    VMCALL_RUN_DRIVER_OBJECT_SCAN,
    VMCALL_TRACE_SYSCALL,
    VMCALL_CHECK_PROCESS_HOLLOWING,
    VMCALL_CHECK_DRIVER_INTEGRITY

} VMCALL_CODE;

#endif
